package io.github.IzumiDIA.constant.enums;

@SuppressWarnings("SpellCheckingInspection")
public enum Color {
	SCROLLBAR,
	BACKGROUND,
	ACTIVECAPTION,
	INACTIVECAPTION,
	MENU,
	WINDOW,
	WINDOWFRAME,
	MENUTEXT,
	WINDOWTEXT,
	CAPTIONTEXT,
	ACTIVEBORDER,
	INACTIVEBORDER,
	APPWORKSPACE,
	HIGHLIGHT,
	HIGHLIGHTTEXT,
	BTNFACE,
	BTNSHADOW,
	GRAYTEXT,
	BTNTEXT,
	INACTIVECAPTIONTEX,
	BTNHIGHLIGHT,
	_3DDKSHADOW,
	_3DLIGHT,
	INFOTEXT,
	INFOBK,
	HOTLIGHT,
	GRADIENTACTIVECAPTION,
	GRADIENTINACTIVECAPTION,
	MENUHILIGHT,
	MENUBAR
	
}
