// Generated by jextract

package org.jextract;

/**
 * {@snippet lang=c :
 * typedef union _LARGE_INTEGER {
 *     struct {
 *         DWORD LowPart;
 *         LONG HighPart;
 *     };
 *     struct {
 *         DWORD LowPart;
 *         LONG HighPart;
 *     } u;
 *     LONGLONG QuadPart;
 * } LARGE_INTEGER
 * }
 */
public class LARGE_INTEGER extends _LARGE_INTEGER {
	
	LARGE_INTEGER() {
		// Should not be called directly
	}
}
