// Generated by jextract

package org.jextract;

/**
 * {@snippet lang=c :
 * typedef struct tagPOINT {
 *     LONG x;
 *     LONG y;
 * } POINT
 * }
 */
public class POINT extends tagPOINT {
	
	POINT() {
		// Should not be called directly
	}
}
