// Generated by jextract

package org.jextract;

/**
 * {@snippet lang=c :
 * typedef struct tagWNDCLASSEXW {
 *     UINT cbSize;
 *     UINT style;
 *     WNDPROC lpfnWndProc;
 *     int cbClsExtra;
 *     int cbWndExtra;
 *     HINSTANCE hInstance;
 *     HICON hIcon;
 *     HCURSOR hCursor;
 *     HBRUSH hbrBackground;
 *     LPCWSTR lpszMenuName;
 *     LPCWSTR lpszClassName;
 *     HICON hIconSm;
 * } WNDCLASSEXW
 * }
 */
public class WNDCLASSEXW extends tagWNDCLASSEXW {
	
	WNDCLASSEXW() {
		// Should not be called directly
	}
}
